Revert "uapi: Export sockaddr_storage for userspace"
Fixes:
soong/.intermediates/bionic/libc/libc/
android_vendor.33_arm_armv8-a_shared/gen/include/sys/socket.h:73:8:
error: redefinition of '__kernel_sockaddr_storage'
struct sockaddr_storage {
       ^
soong/.intermediates/vendor/lineage/build/soong/
generated_kernel_includes/gen/usr/include/linux/socket.h:24:26:
note: expanded from macro 'sockaddr_storage'
 define sockaddr_storage __kernel_sockaddr_storage
                         ^
soong/.intermediates/vendor/lineage/build/soong/
generated_kernel_includes/gen/usr/include/linux/socket.h:13:8:
note: previous definition is here
struct __kernel_sockaddr_storage {
       ^

This reverts commit 1cad9eb8dd5b11ed6b5c906d87ab9c8bf0c7ed81

Change-Id: I1d948c8c1252400e752e006c982080839ebec8ee